add mobile user to sms
lodastack/event pull request #84
Opened 2021-01-25 02:13 UTC by llussy

send username to SendSMS.

2021-01-27 07:22 UTC, oiooj requested changes

2021-01-27 07:22 UTC, oiooj commented on loda/user.go
>  	var i int
clean unused var

2021-01-27 07:23 UTC, oiooj requested changes

2021-01-27 07:23 UTC, oiooj commented on loda/user.go
>  // GetUserMobile return mobile list for users.
update the function's comment.

2021-01-27 08:01 UTC, llussy reviewed
ok

2021-01-28 04:38 UTC, oiooj approved these changes

2021-01-28 04:39 UTC, oiooj commented
LGTM, Thanks @llussy

2021-01-28 04:39 UTC, merged